# Generated by Django 3.2.9 on 2021-11-20 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('secret_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
