# Generated by Django 3.2.9 on 2021-11-18 13:30

import datetime
from django.db import migrations, models
import events_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow, validators=[events_api.models.is_no_from_the_future])),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session_id'], name='session_id_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='category_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='timestamp_idx'),
        ),
    ]
