# Generated by Django 3.2.9 on 2021-11-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('session_id', 'category', 'name', 'timestamp'), name='events_unique'),
        ),
    ]
